name: Deploy Backend

on:
  # En lugar de reaccionar a un push, reacciona a la finalización de otro workflow
  workflow_run:
    workflows: ["Deploy Frontend"] # Este nombre debe ser idéntico al "name:" de tu otro archivo .yml
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # ESTO ES CLAVE: Solo se ejecuta si el frontend terminó sin errores (success)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to VPS y Reiniciar Servicios
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            
            # 1. Traer los últimos cambios
            git pull origin main
            
            # 2. Activar el entorno virtual de Python 3.13.12 y actualizar dependencias
            source venv/bin/activate
            cd ml-backend/
            pip install -r requirement.txt
            
            # 3. Detener el backend anterior si está corriendo
            pkill -f "uvicorn app.main:app" || echo "El proceso no estaba corriendo"
            
            # 4. Iniciar el backend en segundo plano (nohup)
            nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 > backend_nohup.log 2>&1 &
            
            echo "Backend desplegado e iniciado tras la actualización del Frontend"