name: Deploy Backend

on:
  # El backend espera a que el frontend termine
  workflow_run:
    workflows: ["Deploy Frontend"] # Asegúrate de que el archivo del frontend tenga exactamente este "name"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Solo ejecuta si el frontend fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to VPS y Reiniciar Servicios
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /var/www/html
            
            # 1. Traer los últimos cambios
            git pull origin main
            
            # 2. Actualizar dependencias de Python
            source venv/bin/activate
            cd ml-backend/
            pip install -r requirement.txt
            
            # 3. Reiniciar el servicio de Ubuntu (Ahora el usuario github tiene permiso)
            sudo systemctl restart tesisml
            
            echo "Backend actualizado y servicio reiniciado exitosamente."